/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.View1;
import View.ViewLogin;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Welcome extends javax.swing.JFrame {

    private int auxiliar = 0;
    private boolean hecho = false;

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
        Welcome.this.getRootPane().setOpaque(false);
        Welcome.this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        Welcome.this.setBackground(new Color(0, 0, 0, 1));
        this.setResizable(false);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMos = new javax.swing.JLabel();
        gifImagee = new javax.swing.JProgressBar();
        gifImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 310));

        lblMos.setBackground(new java.awt.Color(255, 255, 255));
        lblMos.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        lblMos.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblMos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 275, 240, 20));
        getContentPane().add(gifImagee, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 190, 200, -1));

        gifImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sinfondo.gif"))); // NOI18N
        getContentPane().add(gifImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 70, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (hecho == false) {
            hecho = true;
            gifImagee.setMaximum(100);
            gifImagee.setMinimum(0);
            gifImagee.setStringPainted(true);
        }
    }//GEN-LAST:event_formWindowActivated

    public void Label(int i) {
        for (int j = 1; j <= 100; j++) {
            switch (j) {
                case 1:
                    lblMos.setText("Cargando Programa...");
                    break;
                case 50:
                    lblMos.setText("Leyendo Referencias...");
                    break;
                case 100:
                    lblMos.setText("Carga Finalizada");
                    break;
                default:
                    break;
            }
             gifImagee.setValue(j);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gifImage;
    private javax.swing.JProgressBar gifImagee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMos;
    // End of variables declaration//GEN-END:variables
}
